SRCS = srcs/ft_main.c
CC = gcc
FLAGS =-Wall -Werror -Wextra
RM = rm -rf
NAME = display
${NAME} :
	${CC} ${FLAGS} ${SRCS}
all : ${NAME}
clean : 
	${RM} ${name}

fclean: clean all
re : fclean all
.PHONY: all clean fclean re
